#Prioritizationsettings
weights:
    condition: 0.6
    criticality: 0.4
    
bounds:
    max_damage: 10.0
    max_usage_frequency: 10.0
    
paths:
    input_csv: "data/input_assets.csv"
    output_db: "data/results.db"
    output_geojson: "data/map_data.geojson"