name: Python Pipeline Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Code von GitHub auschecken
      uses: actions/checkout@v4

    - name: Python Version einrichten
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: pip aktualisieren und pytest installieren
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Projekt-Abhängigkeiten installieren
      run: |
        if [ -f requirements ]; then pip install -r requirements; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Pytest automatisiert ausführen
      run: |
        python -m pytest test/